os:
  - osx
  - linux

language: cpp

before_script:
  - wget http://download.savannah.nongnu.org/releases/openexr/ilmbase-2.1.0.tar.gz -O /tmp/ilmbase-2.1.0.tar.gz
  - tar -xzvf /tmp/ilmbase-2.1.0.tar.gz
  - cd ilmbase-2.1.0
  - ./configure --prefix=/usr && make && sudo make install
  - cd $TRAVIS_BUILD_DIR
  - wget http://download.savannah.nongnu.org/releases/openexr/openexr-2.1.0.tar.gz -O /tmp/openexr-2.1.0.tar.gz
  - tar -xzvf /tmp/openexr-2.1.0.tar.gz
  - cd openexr-2.1.0
  - ./configure --prefix=/usr && make && sudo make install
  - cd $TRAVIS_BUILD_DIR
  - wget https://github.com/ampas/aces_container/archive/v1.0.tar.gz -O /tmp/aces_container-1.0.tar.gz
  - tar -xzvf /tmp/aces_container-1.0.tar.gz
  - mkdir aces_container-1.0/build
  - cd aces_container-1.0/build
  - cmake .. && make && sudo make install

script: cd $TRAVIS_BUILD_DIR && mkdir build && cd build && cmake .. && make && make check && sudo make install

