os:
  - osx
  - linux

language: cpp

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libilmbase-dev libopenexr-dev

before_script:
  - wget https://github.com/ampas/aces_container/archive/v1.0.tar.gz -O /tmp/aces_container-1.0.tar.gz
  - tar -xzvf /tmp/aces_container-1.0.tar.gz
  - mkdir aces_container-1.0/build
  - cd aces_container-1.0/build
  - cmake ..
  - make
  - sudo make install

script: mkdir build && cd build && cmake .. && make && make check && sudo make install

